### ISSUE TITLE
Issue with Call Helper Returning Zero Values

### ISSUE THREAD

**Issue by hemantwasthere** [DefiLlama/yield-server#1356]
I am encountering an issue with fetching results from our market stats contract. While the contract provides accurate values, using the call helper function results in zero values being returned from the API.

We are getting this error during the Hashstack market token implementation for the APRs and APYs

PR: #1351 

<img width="604" alt="image" src="https://github.com/DefiLlama/yield-server/assets/85151171/34b248dc-cf8e-43af-ab8f-b4a30e66a256">

**Comment by slasher125** [comment]
merged https://github.com/DefiLlama/yield-server/commit/90901e2d31d1d03ec888c1363017583de9e98791

the issue was that the starknet library wasn't parsing the offset correctly
