### ISSUE TITLE
Request remove hnst from pluto-so yield

### ISSUE THREAD

**Issue by verzth** [DefiLlama/yield-server#1658]
Hi, I want to request removing Staking HNST from yield apy list, we already remove it from API, but it still listed on defillama.

Thanks in advance

**Comment by berryMo27** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [DEFILLAMA SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by verzth** [comment]
This one, https://defillama.com/protocol/pluto#yields
Because HNST not generating any yields, it's only staking for add boost to points.

Thank you, then we will wait until that auto delisted.
