### ISSUE TITLE
simplePools endpoint down?

### ISSUE THREAD

**Issue by chaoticgoodpanda** [DefiLlama/yield-server#324]
Appears to be. In `beforeTests.js`:

`  global.uniquePoolIdentifiersDB = new Set(
    (
      await axios.get(
        'https://1rwmj4tky9.execute-api.eu-central-1.amazonaws.com/simplePools'
      )
    ).data.data
      .filter((p) => p.project !== global.apy[0].project)
      .map((p) => p.pool)
  );`

attempting to run this: `npm run test --adapter=0vix`

Returns this:

`Error: Jest: Got error running globalSetup - reason: [AxiosError: Request failed with status code 404]
    at runGlobalHook (yield-server/node_modules/@jest/core/build/runGlobalHook.js:134:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runJest (yield-server/node_modules/@jest/core/build/runJest.js:372:5)
    at async _run10000 (yield-server/node_modules/@jest/core/build/cli/index.js:339:7)
    at async runCLI (yield-server/node_modules/@jest/core/build/cli/index.js:190:3)
    at async Object.run (yield-server/node_modules/jest-cli/build/cli/index.js:155:37)
`

manually inputting the URL in browser returns 404 in console: https://1rwmj4tky9.execute-api.eu-central-1.amazonaws.com/simplePools.

**Comment by slasher125** [comment]
henlo, seems like u are running on an older version of master. just pull the latest version where we use a different endpoint for during tests

**Comment by chaoticgoodpanda** [comment]
Hmm, just pulled from master, all-files-up-to-date (https://capture.dropbox.com/IQDAOquElVzlkW4w) same error.

**Comment by slasher125** [comment]
can u post the error output again in here? it doesn't make any sense to me tbh. we run this cmd everyday, no issues

**Comment by chaoticgoodpanda** [comment]
You're right -- for some reason wasn't retrieving updated `beforeTests.js` from origin. I manually copied and pasted it for now and will check `gitignore`. Sorry about this! Works now.

**Comment by slasher125** [comment]
all good, glad it works!
