### ISSUE TITLE
Fix number of yield pools for the blueshift adapter

### ISSUE THREAD

**Issue by L0stic** [DefiLlama/yield-server#424]
Only 8 pools are displayed on ui
![image](https://user-images.githubusercontent.com/61114271/199975507-ff5606c5-74e0-41b6-9cbf-863e744706c3.png)
But the adapter gives 9 (https://github.com/DefiLlama/yield-server/pull/416#issuecomment-1302355727)
Last pool is not displayed. Please fix this)

**Comment by slasher125** [comment]
hi. we only show pools with a min of $10k usd in tvl on our UI, which is why you can't see the other one. we apply the same logic across all our projects. closing this
