### ISSUE TITLE
How do you measure APY?

### ISSUE THREAD

**Issue by ruuda** [DefiLlama/yield-server#6]
An annual percentage yield can be defined as follows:

* You start with assets valued at _x_<sub>0</sub> at time _t_<sub>0</sub>.
* At time t<sub>1</sub>, the assets are valued at _x_<sub>1</sub>.
* The growth factor over the period Δ<var>t</var> = _t_<sub>1</sub> – _t_<sub>0</sub> is given by _t_<sub>1</sub>/_t_<sub>0</sub>.
* The annual yield _y_ over the period [_t_<sub>0</sub>, _t_<sub>1</sub>] is then given by _y_(_t_<sub>0</sub>, _t_<sub>1</sub>) = (_x_<sub>1</sub> / _x_<sub>0</sub>)<sup>1 year / Δ<var>t</var></sup> – 1.

Note that it depends on the chosen period. If we want to get the “current” APY, we can set _t_<sub>1</sub> equal to the current time, but what should we choose for _t_<sub>0</sub>?

If this were a continuous process, one could take the limit as _t_<sub>0</sub> → _t_<sub>1</sub> to get an instantaneous APY. But blockchains tend to be discrete; it doesn’t make sense to talk about Δ<var>t</var>’s shorter than the duration of a block, and often values change less frequently (e.g. once per day, or once per epoch). If the valuation has a discontinuity, you can get out any APY you like by looking at a time interval that contains the jump, choosing the size of the interval appropriately. So below a certain time interval, APY becomes meaningless. (You could say, include at least two discontinuities in the interval, but even then, if you look at the “instantaneous” APY, it can swing so wildly that it’s essentially meaningless, similar to how a histogram becomes meaningless if you choose the bin size too small.) This begs the question, over what time interval do you measure APYs?

So just an “APY” value is ambiguous, you always have to specify what time period it’s computed over. Comparing APYs of unspecified periods, is an apples-to-oranges comparison. What period does DefiLlama use?

A related issue is that due to the discrete blocks or epochs, an APY is not always clearly defined at smaller timescales. For example, for [Lido for Solana](https://solana.lido.fi/), the price of one token expressed in some other token started out at 1 at launch, and goes up over time, changing once per epoch. If we take _t_<sub>0</sub> = launch time, and _t_<sub>1</sub> = now, then there is a well-defined time interval to measure APY over, but if you graph that value over time, it looks like a sawtooth, with a high APY at the start of the epoch, which decreases during the epoch. The issue here is that the price is constant for the duration of an epoch, while Δ<var>t</var> increases continuously. One way to resolve this paradox is to say that APY is only defined per epoch (and epochs are discrete), not for any arbitrary moment in time, and that it doesn’t make sense to graph the data at a finer resolution than the epoch. How does DefiLlama deal with this?

**Comment by zhaojun-sh** [comment]
APR is better.

**Comment by slasher125** [comment]
@ruuda , i apologize for replying so late, i read your post initially, then got distracted with everything happening after the launch and completely forgot about it:

thanks for the input, appreciate u taking the time!

```
So just an “APY” value is ambiguous, you always have to specify what time period it’s computed over. Comparing APYs of unspecified periods, is an apples-to-oranges comparison. What period does DefiLlama use?
```

Short answer: 24hours
Longer answer: We gather data “as is” from project subgraphs/contract calls/api’s. we annualise the 24hour fee, where applicable.
As u mentioned, I personally think this is a bit too instantaneous as the chosen period, especially for smaller tvl pools, but its what most projects are doing for their UIs.
At the beginning, my goal was to get the same apr/apy values as displayed on the respective projects frontend. In hindsight, it might have been better if I had gone with a larger window (eg a week) instead. This could be something i might come back to in the future.

**Comment by slasher125** [comment]
Also, checked our api endpoint for the solana apy. ty for sharing, i wasn't aware that they had this. I've been using the endpoint from their homepage: https://lido.fi/
if u check the values u see there, it matches ours. Though u are right, in that case hard to tell what period they use. I'll take a look at yours.

**Comment by ruuda** [comment]
> I personally think this is a bit too instantaneous as the chosen period, especially for smaller tvl pools

It is not related to TVL. At least in the Solana case, staking rewards get paid once per epoch, which is ~3.5 days currently. So yield is not defined at a 24h time scale. There are many other projects where reward payments are discrete.

> I've been using the endpoint from their homepage

This number is inaccurate, we still need to fix this, thanks for pointing that out. The old value was based on an APY estimate from Solana beach, adjusted for fees. But the formula for that was wrong, and it is unknown what Solana Beach’s definition of APY is, so it is unclear what the number means.

> I'll take a look at your proposed one

Of course, you shouldn’t blindly trust some random endpoint on the internet. I can tell you that that endpoint is powered by https://github.com/ChorusOne/solido/blob/b4ba3f7919b9f07b4dad6be7fca1c290467a5328/cli/listener/src/lib.rs, but you shouldn’t just trust me about it, and even if you do right now, that might change in the future. The only trusted way is to run your own RPC nodes and fetch the information from the chain yourself.

**Comment by slasher125** [comment]
> It is not related to TVL. At least in the Solana case, staking rewards get paid once per epoch, which is ~3.5 days currently. So yield is not defined at a 24h time scale. There are many other projects where reward payments are discrete.

In this specific context yes. I was thinking more generally though, eg for balancer pools tvl impacts incentive reward rate. 

> This number is inaccurate, we still need to fix this, thanks for pointing that out. The old value was based on an APY estimate from Solana beach, adjusted for fees. But the formula for that was wrong, and it is unknown what Solana Beach’s definition of APY is, so it is unclear what the number means.

Got it, thanks for explaining!

> Of course, you shouldn’t blindly trust some random endpoint on the internet. I can tell you that that endpoint is powered by https://github.com/ChorusOne/solido/blob/b4ba3f7919b9f07b4dad6be7fca1c290467a5328/cli/listener/src/lib.rs, but you shouldn’t just trust me about it, and even if you do right now, that might change in the future. The only trusted way is to run your own RPC nodes and fetch the information from the chain yourself.

heh, yes! Own implementation would be best agree! I will update the adaptor using this endpoint for now. will go with 14days period

**Comment by slasher125** [comment]
Closing this :)
