### ISSUE TITLE
Borrow aggregator: FiRM protocol - negative liquidity

### ISSUE THREAD

**Issue by webmass** [DefiLlama/yield-server#832]
Hello
I noticed the liquidity is negative for some of the markets regarding the Inverse Finance - FiRM protocol.

It seems the calculation that is shown for the "available" column is the `liquidity minus amount borrowed` instead of just the liquidity.

**Comment by slasher125** [comment]
ty for reporting. fixed here https://github.com/DefiLlama/yield-server/commit/54e931a34715b848b1ddefa658f3e8541d67a727
for cdps we calc available liquidity as max debt ceiling - borrowed
