### ISSUE TITLE
different apyBase in different location

### ISSUE THREAD

**Issue by dev-aly3n** [DefiLlama/yield-server#970]
Hi, I'm using yield charts data for our app. but the last data of API is not stable and is different in different locations.
for example try to open this link in other location (countries)

https://yields.llama.fi/chart/7aab7b0f-01c1-4467-bc0d-77826d870f19

![image_2023-08-28_18-09-40](https://github.com/DefiLlama/yield-server/assets/79654879/3da4326d-1959-4860-b2ba-26bf3e698df2)
![image_2023-08-28_18-11-02](https://github.com/DefiLlama/yield-server/assets/79654879/f055e336-96e4-454e-aba8-ed56a09afea3)

look at these images. they have been taken in a same time in different countries but you can see the last item is not same.
we use the last base apy to calculate best leverage for a position. and this behavior break our calculation.

**Comment by slasher125** [comment]
generally, data from /chart is cached for 24h.
therefore, i suggest to pull /pools instead which has a cache of 1h only
